"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, CheckCircle2, Database, FileWarning, LoaderCircle, Settings as SettingsIcon } from "lucide-react";
import { Dashboard } from "@/components/Dashboard";
import { SettingsDrawer } from "@/components/SettingsDrawer";
import { UploadPanel } from "@/components/UploadPanel";
import { ValidationSummary } from "@/components/ValidationSummary";
import { matchAndCalculate, validation } from "@/lib/analysis/matching";
import { exportResults } from "@/lib/excel/exporter";
import { parseTelecomWorkbook } from "@/lib/excel/parser";
import { defaultSettings, type ParseResult, type Settings } from "@/lib/types/telecom";

type Stage = "idle" | "reading-before" | "reading-after" | "matching" | "done";
export default function Home() {
  const [beforeFile, setBeforeFile] = useState<File>(); const [afterFile, setAfterFile] = useState<File>(); const [before, setBefore] = useState<ParseResult>(); const [after, setAfter] = useState<ParseResult>(); const [stage, setStage] = useState<Stage>("idle"); const [error, setError] = useState<string>(); const [settings, setSettings] = useState<Settings>(defaultSettings); const [settingsOpen, setSettingsOpen] = useState(false);
  const summary = useMemo(() => before && after ? validation(before, after) : undefined, [before, after]); const results = useMemo(() => before && after ? matchAndCalculate(before, after, settings) : [], [before, after, settings]);
  useEffect(() => { if (!beforeFile || !afterFile) return; let cancelled = false; const validateFiles = async () => { setError(undefined); setBefore(undefined); setAfter(undefined); try { setStage("reading-before"); const parsedBefore = await parseTelecomWorkbook(beforeFile); if (cancelled) return; setStage("reading-after"); const parsedAfter = await parseTelecomWorkbook(afterFile); if (cancelled) return; setBefore(parsedBefore); setAfter(parsedAfter); setStage("idle"); } catch (e) { if (!cancelled) { setStage("idle"); setError(e instanceof Error ? e.message : "Une erreur est survenue pendant la validation des fichiers."); } } }; void validateFiles(); return () => { cancelled = true; }; }, [beforeFile, afterFile]);
  const analyze = async () => { if (!before || !after) return; setStage("matching"); await new Promise((resolve) => setTimeout(resolve, 100)); setStage("done"); };
  const reset = () => { setBeforeFile(undefined); setAfterFile(undefined); setBefore(undefined); setAfter(undefined); setError(undefined); setStage("idle"); };
  if (stage === "done" && before && after) return <><Dashboard results={results} allResults={results} beforeRecords={[...before.records.values()]} afterRecords={[...after.records.values()]} onChangeFiles={reset} onSettings={() => setSettingsOpen(true)} onExport={(items) => exportResults(items, results, settings, beforeFile?.name || "BEFORE", afterFile?.name || "AFTER")} /><SettingsDrawer open={settingsOpen} settings={settings} onClose={() => setSettingsOpen(false)} onApply={setSettings}/></>;
  const stageText: Record<Exclude<Stage,"idle"|"done">, string> = { "reading-before": "Lecture du fichier BEFORE", "reading-after": "Lecture du fichier AFTER", matching: "Appariement et calcul TRD / IEA" };
  return <main className="upload-page"><header className="landing-header"><div className="brand"><span className="brand-mark"><Activity size={22}/></span><div><b>NETWORK PERFORMANCE</b><small>ANALYTICS</small></div></div><button className="settings-trigger" onClick={() => setSettingsOpen(true)}><SettingsIcon size={17}/> Paramètres méthodologiques</button></header><section className="upload-hero"><span className="eyebrow">QUALIFICATION D’ACTION RADIO</span><h1>Network Action<br/><em>Effectiveness Analyzer</em></h1><p>TRD / IEA – Before vs After KPI Qualification</p><div className="privacy"><Database size={15}/> Les fichiers sont analysés localement dans votre navigateur et ne sont pas conservés par l’application.</div></section><section className="upload-workspace"><div className="workflow"><span className="active">01 <b>Import</b></span><i/><span>02 <b>Validation</b></span><i/><span>03 <b>Analyse</b></span><i/><span>04 <b>Dashboard</b></span></div><div className="upload-grid"><UploadPanel label="BEFORE" description="Baseline avant action corrective" file={beforeFile} onFile={(f) => { setBeforeFile(f); setBefore(undefined); setAfter(undefined); setStage("idle"); }}/><div className="comparison-arrow"><ArrowRight size={24}/></div><UploadPanel label="AFTER" description="Qualification après action corrective" file={afterFile} onFile={(f) => { setAfterFile(f); setBefore(undefined); setAfter(undefined); setStage("idle"); }}/></div>{error && <div className="error-box"><FileWarning size={20}/><div><b>Impossible de préparer l’analyse</b><span>{error}</span></div></div>}{summary && <ValidationSummary summary={summary}/>}<div className="analyze-row"><div><CheckCircle2 size={18}/><span>Comparaison par secteur · Dégradation initiale conservée comme référence</span></div><button className="analyze-button" disabled={!before || !after || stage !== "idle"} onClick={analyze}>{stage === "idle" ? <>Analyser l’impact <ArrowRight size={18}/></> : <><LoaderCircle className="spin" size={18}/> {stageText[stage as Exclude<Stage,"idle"|"done">]}</>}</button></div></section><section className="method-note"><div><span>TRD</span><p>Mesure la part de la dégradation initiale réellement résorbée.</p></div><div><span>IEA</span><p>Indice synthétique d’efficacité, débit 60 % et PRB 40 % par défaut.</p></div><div><span>2 SNAPSHOTS</span><p>Qualification indicative : contrôlez BH, trafic et utilisateurs pour confirmer la causalité.</p></div></section><SettingsDrawer open={settingsOpen} settings={settings} onClose={() => setSettingsOpen(false)} onApply={setSettings}/></main>;
}
