"use client";
import { ChevronDown, Download, FilterX, Info, Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BANDS, type Band, type SectorImpactResult } from "@/lib/types/telecom";
import { QualificationTables } from "@/components/QualificationTables";
import type { SectorSnapshot } from "@/lib/types/telecom";

const colors: Record<string, string> = { "Très efficace": "#16835f", Efficace: "#1a9c76", "Amélioration partielle": "#d69119", "Impact faible / non significatif": "#8091a5", "Régression": "#d65050", "Non mesurable": "#b3bdc9" };
const statuses = Object.keys(colors);
const pct = (value?: number) => value === undefined ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)} %`;
const points = (value?: number) => value === undefined ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(1)} pts`;
const date = (value?: Date) => value ? new Intl.DateTimeFormat("fr-FR").format(value) : "—";
const median = (values: number[]) => { const copy = values.sort((a,b) => a-b); return copy.length ? copy[Math.floor(copy.length/2)] : undefined; };
function unique(values: (string | undefined)[]) { return [...new Set(values.filter(Boolean) as string[])].sort((a,b) => a.localeCompare(b)); }
function statusClass(status: string) { return `status ${status === "Très efficace" || status === "Efficace" ? "success" : status === "Amélioration partielle" ? "partial" : status === "Régression" ? "danger" : "neutral"}`; }
type MultiFilterKey = "situation" | "dr" | "plaque" | "vendor" | "responsibility" | "qualif" | "band" | "effectiveness";
type Filters = { search: string; min: string; max: string } & Record<MultiFilterKey, string[]>;
const emptyFilters: Filters = { search: "", situation: [], dr: [], plaque: [], vendor: [], responsibility: [], qualif: [], band: [], effectiveness: [], min: "", max: "" };

export function Dashboard({ results, allResults, beforeRecords, afterRecords, onChangeFiles, onSettings, onExport }: { results: SectorImpactResult[]; allResults: SectorImpactResult[]; beforeRecords: SectorSnapshot[]; afterRecords: SectorSnapshot[]; onChangeFiles: () => void; onSettings: () => void; onExport: (items: SectorImpactResult[]) => void }) {
  const [filters, setFilters] = useState<Filters>(emptyFilters); const [selected, setSelected] = useState<SectorImpactResult>(); const [sort, setSort] = useState<"iea" | "sector">("iea"); const [metric, setMetric] = useState<"median" | "average">("median");
  const filtered = useMemo(() => results.filter((r) => (!filters.search || r.sector.toLowerCase().includes(filters.search.toLowerCase())) && (!filters.situation.length || filters.situation.includes(r.after.situation || "")) && (!filters.dr.length || filters.dr.includes(r.after.dr || "")) && (!filters.plaque.length || filters.plaque.includes(r.after.plaque || "")) && (!filters.vendor.length || filters.vendor.includes(r.after.vendor || "")) && (!filters.responsibility.length || filters.responsibility.includes(r.after.responsibility || "")) && (!filters.qualif.length || filters.qualif.includes(r.degradationStatus)) && (!filters.band.length || filters.band.some((band) => r.before.degradedBands.includes(band as Band) || r.before.chargedBands.includes(band as Band))) && (!filters.effectiveness.length || filters.effectiveness.includes(r.actionEffectiveness)) && (!filters.min || (r.iea ?? -Infinity) >= Number(filters.min) / 100) && (!filters.max || (r.iea ?? Infinity) <= Number(filters.max) / 100)), [results, filters]);
  const measurable = filtered.filter((r) => r.iea !== undefined); const avgIea = measurable.length ? measurable.reduce((s, r) => s + (r.iea || 0), 0) / measurable.length : undefined; const persistentImprovement = filtered.filter((r) => /^persiste/i.test(r.degradationStatus) && (r.iea ?? -Infinity) >= .2).length;
  const qualificationUniqueCount = new Set(afterRecords.map((record) => record.sector)).size;
  const qualificationDuplicates = afterRecords.length - qualificationUniqueCount;
  const distribution = statuses.map((status) => ({ name: status.replace("Impact faible / non significatif", "Impact faible").replace("Amélioration partielle", "Partielle"), full: status, count: filtered.filter((r) => r.actionEffectiveness === status).length, pct: filtered.length ? filtered.filter((r) => r.actionEffectiveness === status).length / filtered.length : 0 }));
  const responsibilities = Object.entries(filtered.reduce<Record<string, SectorImpactResult[]>>((acc, r) => { const key = r.after.responsibility || "Non renseigné"; (acc[key] ||= []).push(r); return acc; }, {})).map(([name, group]) => { const m = group.filter((r) => r.iea !== undefined); return { name, sectors: group.length, measurable: m.length, iea: m.length ? m.reduce((s, r) => s + (r.iea || 0), 0) / m.length : 0 }; }).sort((a,b) => b.iea-a.iea);
  const matrixStatuses = ["Normalisé", "Persiste", "Compromis"]; const matrix = matrixStatuses.map((label) => ({ name: label, ...Object.fromEntries(statuses.slice(0,5).map((status) => [status, filtered.filter((r) => r.degradationStatus.toLowerCase().startsWith(label.toLowerCase()) && r.actionEffectiveness === status).length])) }));
  const bandData = BANDS.map((band) => { const gains = filtered.map((r) => r.bandResults[band].throughputGain).filter((v): v is number => v !== undefined); const relief = filtered.map((r) => r.bandResults[band].prbRelief).filter((v): v is number => v !== undefined); const reducer = (arr:number[]) => metric === "median" ? median(arr) : arr.length ? arr.reduce((a,b)=>a+b,0)/arr.length : undefined; return { band, gain: (reducer(gains) || 0) * 100, relief: reducer(relief) || 0 }; });
  const sorted = [...filtered].sort((a,b) => sort === "sector" ? a.sector.localeCompare(b.sector) : (b.iea ?? -Infinity) - (a.iea ?? -Infinity)); const top = [...measurable].sort((a,b)=>(b.iea||0)-(a.iea||0)).slice(0,10).map(r=>({name:r.sector,iea:(r.iea||0)*100})); const bottom = [...measurable].sort((a,b)=>(a.iea||0)-(b.iea||0)).slice(0,10).map(r=>({name:r.sector,iea:(r.iea||0)*100}));
  const filtersActive = filters.search !== "" || filters.min !== "" || filters.max !== "" || Object.entries(filters).some(([key, value]) => key !== "search" && key !== "min" && key !== "max" && Array.isArray(value) && value.length > 0);
  const qualificationAfter = filtersActive ? filtered.map((result) => result.after) : afterRecords;
  const qualificationBefore = filtersActive ? filtered.map((result) => result.before) : beforeRecords;
  const select = (key: MultiFilterKey, label: string, options: string[]) => <MultiSelect label={label} options={options} value={filters[key]} onChange={(value) => setFilters({ ...filters, [key]: value })} />;
  return <main className="app-shell"><header className="dashboard-header"><div><span className="eyebrow">ANALYSE FINALISÉE</span><h1>Network Action Effectiveness Analyzer</h1><p>TRD / IEA · Qualification avant vs après KPI</p></div><div className="header-actions"><button className="outline" onClick={onChangeFiles}>Changer les fichiers</button><button className="outline" onClick={onSettings}><SlidersHorizontal size={16}/> Paramètres</button><div className="export-menu"><button className="primary"><Download size={16}/> Export Excel</button><div><button onClick={() => onExport(allResults)}>Exporter tout</button><button onClick={() => onExport(filtered)}>Exporter filtré</button></div></div></div></header>
    <section className="filter-bar"><div className="filter-title"><Search size={16}/><input placeholder="Rechercher un secteur…" value={filters.search} onChange={(e) => setFilters({...filters, search:e.target.value})}/></div>{select("situation", "Situation", unique(results.map(r=>r.after.situation)))}{select("dr", "DR", unique(results.map(r=>r.after.dr)))}{select("plaque", "Plaque", unique(results.map(r=>r.after.plaque)))}{select("vendor", "Vendor", unique(results.map(r=>r.after.vendor)))}{select("responsibility", "Responsabilité", unique(results.map(r=>r.after.responsibility)))}{select("qualif", "Qualif", unique(results.map(r=>r.degradationStatus)))}{select("band", "Bande", [...BANDS])}{select("effectiveness", "IEA", statuses)}<label className="range"><span>IEA</span><input placeholder="min" inputMode="decimal" value={filters.min} onChange={e=>setFilters({...filters,min:e.target.value})}/><i>–</i><input placeholder="max" inputMode="decimal" value={filters.max} onChange={e=>setFilters({...filters,max:e.target.value})}/></label><button className="reset" onClick={() => setFilters(emptyFilters)}><FilterX size={15}/> Réinitialiser</button></section>
    <div className="showing"><b>{filtered.length}</b> secteurs affichés / {allResults.length} au total</div>
    <section className="kpi-grid"><Kpi label="Lignes qualification finale" value={String(afterRecords.length)} sub={`${qualificationUniqueCount} secteurs uniques · ${qualificationDuplicates} doublons`} icon="◉"/><Kpi label="Actions mesurables" value={String(measurable.length)} sub={filtered.length ? `${(measurable.length/filtered.length*100).toFixed(0)} % du périmètre` : "—"} icon="✓"/><Kpi label="Secteurs normalisés" value={String(filtered.filter(r=>/^normalis/i.test(r.degradationStatus)).length)} sub="qualification AFTER" icon="↗"/><Kpi label="Persiste avec amélioration" value={String(persistentImprovement)} sub={filtered.filter(r=>/^persiste/i.test(r.degradationStatus)).length ? `${(persistentImprovement/filtered.filter(r=>/^persiste/i.test(r.degradationStatus)).length*100).toFixed(0)} % des persistants` : "—"} icon="≈"/><Kpi label="Régressions" value={String(filtered.filter(r=>r.actionEffectiveness==="Régression").length)} sub="IEA inférieur à −20 %" icon="↓" danger/><Kpi label="IEA moyen" value={pct(avgIea)} sub="actions mesurables" icon="◆" accent/></section>
    <section className="charts-grid"><ChartCard title="Distribution de l'efficacité" subtitle="Cliquez sur une barre pour filtrer le tableau de bord"><ResponsiveContainer width="100%" height={260}><BarChart data={distribution}><CartesianGrid vertical={false} stroke="#e9eef4"/><XAxis dataKey="name" tick={{fontSize:11}} interval={0}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" radius={[4,4,0,0]}>{distribution.map((e)=><Cell key={e.full} className="effectiveness-bar" fill={colors[e.full]} onClick={() => setFilters({ ...filters, effectiveness: [e.full] })}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="IEA moyen par responsabilité" subtitle="Trié par efficacité moyenne"><ResponsiveContainer width="100%" height={260}><BarChart data={responsibilities} layout="vertical" margin={{left:20}}><CartesianGrid horizontal={false} stroke="#e9eef4"/><XAxis type="number" tickFormatter={(v)=>`${v*100}%`}/><YAxis dataKey="name" type="category" width={120} tick={{fontSize:11}}/><Tooltip formatter={(v:number)=>pct(v)}/><Bar dataKey="iea" fill="#235c9e" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Statut de dégradation vs efficacité" subtitle="Persiste ne signifie pas action inefficace"><ResponsiveContainer width="100%" height={260}><BarChart data={matrix}><CartesianGrid vertical={false} stroke="#e9eef4"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend wrapperStyle={{fontSize:10}}/>{statuses.slice(0,5).map(s=><Bar key={s} dataKey={s} stackId="a" fill={colors[s]}/>)}</BarChart></ResponsiveContainer></ChartCard><ChartCard title="Évolution par bande" subtitle={`${metric === "median" ? "Médiane" : "Moyenne"} · débit et soulagement PRB`} actions={<button className="chart-toggle" onClick={()=>setMetric(metric==="median"?"average":"median")}>{metric === "median" ? "Passer à moyenne" : "Passer à médiane"}</button>}><ResponsiveContainer width="100%" height={260}><BarChart data={bandData}><CartesianGrid vertical={false} stroke="#e9eef4"/><XAxis dataKey="band"/><YAxis/><Tooltip/><Legend/><Bar dataKey="gain" name="Gain débit (%)" fill="#19815f" radius={[4,4,0,0]}/><Bar dataKey="relief" name="Soulagement PRB (pts)" fill="#d99a28" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Top 10 améliorations" subtitle="IEA le plus élevé"><RankChart data={top} fill="#19815f" /></ChartCard><ChartCard title="Top 10 régressions" subtitle="IEA le plus faible"><RankChart data={bottom} fill="#d65050" /></ChartCard></section>
    <QualificationTables before={qualificationBefore} after={qualificationAfter}/><section className="table-section"><div className="section-heading"><div><span className="eyebrow">DÉTAIL SECTEUR</span><h2>Résultats TRD / IEA</h2></div><label className="sort">Trier par <select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="iea">IEA décroissant</option><option value="sector">Secteur</option></select></label></div><div className="results-wrap"><table><thead><tr><th>Secteur</th><th>DR</th><th>Responsabilité</th><th>Action</th><th>Date action</th><th>Dégradation initiale</th><th>TRD Débit <Info size={13}/></th><th>TRD PRB <Info size={13}/></th><th>IEA</th><th>Efficacité</th><th>Qualif</th><th>Conclusion</th></tr></thead><tbody>{sorted.map(r=><tr key={r.id} onClick={()=>setSelected(r)}><td><button className="sector-link">{r.sector}</button></td><td>{r.after.dr||"—"}</td><td>{r.after.responsibility||"—"}</td><td className="action-cell">{r.after.action||"—"}</td><td>{date(r.dateAction)}</td><td>{r.before.degradedBands.join(" + ")||"—"}</td><td className={r.trdThroughput !== undefined && r.trdThroughput < 0 ? "negative" : "positive"}>{pct(r.trdThroughput)}</td><td className={r.trdPrb !== undefined && r.trdPrb < 0 ? "negative" : "positive"}>{pct(r.trdPrb)}</td><td className={r.iea !== undefined && r.iea < 0 ? "negative" : "positive"}>{pct(r.iea)}</td><td><span className={statusClass(r.actionEffectiveness)}>{r.actionEffectiveness}</span></td><td>{r.degradationStatus}</td><td>{r.conclusion}</td></tr>)}</tbody></table>{!sorted.length && <div className="empty">Aucun secteur ne correspond aux filtres actifs.</div>}</div></section>{selected && <SectorDrawer result={selected} onClose={()=>setSelected(undefined)} />}</main>;
}
function MultiSelect({ label, options, value, onChange }: { label: string; options: string[]; value: string[]; onChange: (next: string[]) => void }) { const [open, setOpen] = useState(false); const [contains, setContains] = useState(""); const toggle = (option: string) => onChange(value.includes(option) ? value.filter((item) => item !== option) : [...value, option]); const visible = options.filter((option) => option.toLowerCase().includes(contains.toLowerCase())); return <div className="filter-select multi-select"><span>{label}</span><button type="button" className="multi-select-button" onClick={() => setOpen(!open)} aria-expanded={open}>{value.length ? `${value.length} sélectionné${value.length > 1 ? "s" : ""}` : "Tous"}<ChevronDown size={14}/></button>{open && <div className="multi-select-menu"><input className="contains-input" placeholder="Contient…" value={contains} onChange={(event) => setContains(event.target.value)}/><div className="multi-select-actions"><button type="button" onClick={() => onChange([])}>Tout effacer</button><button type="button" onClick={() => onChange([...options])}>Tout choisir</button></div>{visible.map((option) => <label key={option}><input type="checkbox" checked={value.includes(option)} onChange={() => toggle(option)}/><span>{option}</span></label>)}{!visible.length && <p className="no-filter-option">Aucune valeur correspondante</p>}</div>}</div>; }
function Kpi({label,value,sub,icon,danger,accent}:{label:string;value:string;sub:string;icon:string;danger?:boolean;accent?:boolean}) { return <article className={`kpi ${danger?"kpi-danger":""} ${accent?"kpi-accent":""}`}><span className="kpi-icon">{icon}</span><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>; }
function ChartCard({title,subtitle,actions,children}:{title:string;subtitle:string;actions?:React.ReactNode;children:React.ReactNode}) { return <article className="chart-card"><div className="chart-heading"><div><h3>{title}</h3><p>{subtitle}</p></div>{actions}</div>{children}</article>; }
function RankChart({data,fill}:{data:{name:string;iea:number}[];fill:string}) { return <ResponsiveContainer width="100%" height={260}><BarChart data={data} layout="vertical" margin={{left:20}}><CartesianGrid horizontal={false} stroke="#e9eef4"/><XAxis type="number" tickFormatter={(v)=>`${v}%`}/><YAxis dataKey="name" type="category" width={120} tick={{fontSize:10}}/><Tooltip formatter={(v:number)=>`${v.toFixed(1)} %`}/><Bar dataKey="iea" fill={fill} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer>; }
function SectorDrawer({result,onClose}:{result:SectorImpactResult;onClose:()=>void}) { return <><div className="drawer-backdrop" onClick={onClose}/><aside className="sector-drawer"><div className="drawer-title"><div><span>SECTEUR</span><h2>{result.sector}</h2></div><button onClick={onClose}><X/></button></div><div className="sector-meta"><div><span>Responsabilité</span><b>{result.after.responsibility||"—"}</b></div><div><span>Action</span><b>{result.after.action||"—"}</b></div><div><span>Date action</span><b>{date(result.dateAction)}</b></div><div><span>Qualification</span><b>{result.degradationStatus}</b></div></div><div className="detail-kpis"><Kpi label="TRD Débit" value={pct(result.trdThroughput)} sub="résorption initiale" icon="↗"/><Kpi label="TRD PRB" value={pct(result.trdPrb)} sub="résorption initiale" icon="↘"/><Kpi label="IEA Action" value={pct(result.iea)} sub={result.actionEffectiveness} icon="◆" accent/></div><p className="conclusion"><strong>{result.conclusion}</strong><br/>{result.confidence}</p><h3>Comparaison par bande</h3><div className="results-wrap detail-table"><table><thead><tr><th>Bande</th><th>DL avant</th><th>DL après</th><th>Gain DL</th><th>PRB avant</th><th>PRB après</th><th>Relief PRB</th></tr></thead><tbody>{BANDS.map(b=>{const x=result.bandResults[b];return <tr className={x.initiallyDegraded||x.initiallyCharged?"initial-band":""} key={b}><td>{b}</td><td>{x.throughputBefore??"—"}</td><td>{x.throughputAfter??"—"}</td><td className={x.throughputGain!==undefined&&x.throughputGain<0?"negative":"positive"}>{pct(x.throughputGain)}</td><td>{x.prbBefore??"—"}</td><td>{x.prbAfter??"—"}</td><td className={x.prbRelief!==undefined&&x.prbRelief<0?"negative":"positive"}>{points(x.prbRelief)}</td></tr>})}</tbody></table></div><div className="mini-chart"><ResponsiveContainer width="100%" height={180}><BarChart data={BANDS.map(b=>({band:b,before:result.bandResults[b].throughputBefore,after:result.bandResults[b].throughputAfter}))}><XAxis dataKey="band"/><YAxis/><Tooltip/><Legend/><Bar dataKey="before" name="DL avant" fill="#9bb4cf"/><Bar dataKey="after" name="DL après" fill="#235c9e"/></BarChart></ResponsiveContainer></div></aside></>; }
