"use client";

import { X } from "lucide-react";
import { BANDS, type Settings } from "@/lib/types/telecom";

const pct = (value: number) => `${(value * 100).toFixed(0)} %`;

export function MethodologyDrawer({ open, settings, onClose }: { open: boolean; settings: Settings; onClose: () => void }) {
  if (!open) return null;
  return <><div className="drawer-backdrop" onClick={onClose}/><aside className="methodology-drawer"><div className="drawer-title"><div><span>MÉTHODOLOGIE</span><h2>IEA-R / IEA-E</h2></div><button onClick={onClose} aria-label="Fermer"><X/></button></div><div className="methodology-body">
    <p className="methodology-intro"><b>IEA-R — Résorption</b> mesure ce que l’action a résorbé sur les bandes initialement dégradées ou chargées. <b>IEA-E — Évolution</b> mesure toute amélioration ou régression des KPI entre BEFORE et AFTER, y compris sur une bande saine au départ.</p>
    <section><h3>1. KPI BEFORE et trafic de référence</h3><p>La référence Ookla est prioritaire pour les secteurs correspondants ; le fichier BEFORE est le repli. Le trafic de référence est un poids fixe pour IEA-E, pas un KPI de performance. Availability et TA restent informatifs.</p></section>
    <section><h3>2. IEA-R — Résorption historique</h3><p>L’IEA-R conserve exactement la méthode historique. Seules les bandes déclarées dégradées ou chargées dans BEFORE sont évaluées.</p><div className="formula-box"><b>TRD Débit</b><span>1 − Gap DL AFTER / Gap DL BEFORE</span><b>TRD PRB</b><span>1 − Gap PRB AFTER / Gap PRB BEFORE</span><b>IEA-R</b><span>{pct(settings.throughputWeight)} × TRD Débit + {pct(settings.prbWeight)} × TRD PRB</span></div><p>Seuils DL : {BANDS.map((band) => `${band} ${settings.dlThresholds[band]} Mbps`).join(" · ")}. Seuil PRB : {settings.prbThreshold} %.</p></section>
    <section><h3>3. IEA-E — Score par bande</h3><div className="formula-box"><b>Score DL</b><span>(DL après − DL avant) / max(DL après, DL avant)</span><b>Score PRB</b><span>(PRB avant − PRB après) / 100</span><b>IEA-E bande</b><span>{pct(settings.throughputWeight)} × Score DL + {pct(settings.prbWeight)} × Score PRB</span></div><p>Le score DL est borné entre −100 % et +100 %. Une baisse de PRB est positive. Si un seul KPI est comparable, son poids est renormalisé à 100 % et la couverture est indiquée « Partielle ». Lorsqu’un KPI comparable est strictement stable et que l’autre varie, le KPI qui évolue est aussi renormalisé à 100 % : ainsi DL 21 → 19 avec PRB stable garde un score de −9,5 %.</p><p>Sont exclus : débit négatif, deux débits nuls, PRB hors [0, 100].</p></section>
    <section><h3>4. IEA-E secteur et contribution globale</h3><div className="formula-box"><b>IEA-E secteur</b><span>Σ (trafic bande × IEA-E bande) / Σ trafic bandes</span><b>Contribution responsabilité</b><span>Σ (trafic secteur × IEA-E secteur) / Σ trafic total éligible</span></div><p>Si toutes les bandes comparables possèdent un trafic positif, la pondération trafic est utilisée et le secteur est éligible à la contribution globale. Sinon, les bandes reçoivent des poids égaux : « Pondération de secours ». Le secteur reste visible, mais est exclu du global pondéré.</p></section>
    <section><h3>5. Qualification IEA-E</h3><table className="methodology-table"><tbody><tr><td>Forte amélioration</td><td>IEA-E ≥ {pct(settings.evolutionStrong)}</td></tr><tr><td>Amélioration</td><td>{pct(settings.evolutionStable)} ≤ IEA-E &lt; {pct(settings.evolutionStrong)}</td></tr><tr><td>Stable / non significatif</td><td>−{pct(settings.evolutionStable)} &lt; IEA-E &lt; {pct(settings.evolutionStable)}</td></tr><tr><td>Régression</td><td>−{pct(settings.evolutionStrong)} &lt; IEA-E ≤ −{pct(settings.evolutionStable)}</td></tr><tr><td>Forte régression</td><td>IEA-E ≤ −{pct(settings.evolutionStrong)}</td></tr><tr><td>Non mesurable</td><td>Aucun KPI comparable</td></tr></tbody></table><p>Exemple : DL 21 → 19 et PRB 36 → 67 donnent 60 % × −9,5 % + 40 % × −31 % = <b>−18,1 % : Régression</b>.</p></section>
    <section><h3>6. Lecture des résultats</h3><p>Le statut de dégradation (Normalisé, Persiste, Compromis…) vient du fichier AFTER. IEA-R et IEA-E sont des mesures distinctes : une bande saine qui régresse apparaît en IEA-E, tout en restant hors périmètre IEA-R.</p><p className="methodology-note">Comparaison indicative sur deux snapshots : pour une causalité forte, comparez des fenêtres BH homogènes et contrôlez trafic et utilisateurs.</p></section>
  </div></aside></>;
}
