"use client";

import type { SectorSnapshot } from "@/lib/types/telecom";

type SummaryRow = { responsibility: string; actions: number; normalized: number; compromised: number; completed: number; persistent: number };
const normal = (value?: string) => /^normalis/i.test(value?.normalize("NFD").replace(/[\u0300-\u036f]/g, "") || "");
const compromised = (value?: string) => /^compromis/i.test(value || "");
const persistent = (value?: string) => /^persiste/i.test(value || "");
const responsibility = (value?: string) => { const text = (value || "Non renseigné").trim(); return text.toLowerCase() === "maintenance" ? "Maintenance" : text; };

export function QualificationTables({ before, after, isFiltered }: { before: SectorSnapshot[]; after: SectorSnapshot[]; isFiltered: boolean }) {
  const beforeBySector = new Map(before.map((item) => [item.sector, item]));
  const uniqueSectorCount = new Set(after.map((item) => item.sector)).size;
  const duplicateCount = after.length - uniqueSectorCount;
  const grouped = new Map<string, SummaryRow>();
  after.forEach((item) => { const key = responsibility(item.responsibility); const row = grouped.get(key) || { responsibility: key, actions: 0, normalized: 0, compromised: 0, completed: 0, persistent: 0 }; row.actions++; if (normal(item.qualif)) row.normalized++; else if (compromised(item.qualif)) row.compromised++; else if (persistent(item.qualif)) row.persistent++; else row.completed++; grouped.set(key, row); });
  const qualificationRows = [...grouped.values()].sort((a, b) => a.responsibility.localeCompare(b.responsibility));
  const movements = new Map<string, { responsibility: string; normalized: number; newDegradation: number }>();
  after.forEach((item) => { const baseline = beforeBySector.get(item.sector); const key = responsibility(item.responsibility); const row = movements.get(key) || { responsibility: key, normalized: 0, newDegradation: 0 }; if (!baseline) row.newDegradation++; else { if (!normal(baseline.qualif) && normal(item.qualif)) row.normalized++; if (normal(baseline.qualif) && !normal(item.qualif)) row.newDegradation++; } movements.set(key, row); });
  const movementRows = [...movements.values()].filter((row) => row.normalized || row.newDegradation).sort((a, b) => a.responsibility.localeCompare(b.responsibility));
  const totals = qualificationRows.reduce((total, row) => ({ responsibility: "Total", actions: total.actions + row.actions, normalized: total.normalized + row.normalized, compromised: total.compromised + row.compromised, completed: total.completed + row.completed, persistent: total.persistent + row.persistent }), { responsibility: "Total", actions: 0, normalized: 0, compromised: 0, completed: 0, persistent: 0 });
  const movementTotal = movementRows.reduce((total, row) => ({ normalized: total.normalized + row.normalized, newDegradation: total.newDegradation + row.newDegradation }), { normalized: 0, newDegradation: 0 });
  return <section className="qualification-section"><div className="section-heading"><div><span className="eyebrow">QUALIFICATION FINALE</span><h2>Synthèse opérationnelle</h2></div><p>Calculée sur le fichier AFTER, avec évolution comparée au BEFORE.</p></div><p className="qualification-scope"><strong>{isFiltered ? "Périmètre filtré" : "Périmètre complet"}</strong> · {after.length} lignes · {uniqueSectorCount} secteurs uniques · <span>{duplicateCount} doublons</span></p><div className="qualification-table-wrap"><table className="qualification-table"><thead><tr><th>Responsabilité</th><th>Nombre d&apos;actions</th><th className="normalized-head">Normalisé</th><th className="compromised-head">Compromis</th><th className="completed-head">Action réalisé / Persiste</th><th className="persistent-head">Persiste</th></tr></thead><tbody>{qualificationRows.map((row) => <tr key={row.responsibility}><td>{row.responsibility}</td><td>{row.actions}</td><td className="normalized-cell">{row.normalized}</td><td className="compromised-cell">{row.compromised || ""}</td><td className="completed-cell">{row.completed || ""}</td><td className="persistent-cell">{row.persistent || ""}</td></tr>)}<tr className="total-row"><td>Total</td><td>{totals.actions}</td><td className="normalized-cell">{totals.normalized}</td><td className="compromised-cell">{totals.compromised || ""}</td><td className="completed-cell">{totals.completed || ""}</td><td className="persistent-cell">{totals.persistent || ""}</td></tr></tbody></table></div><h3 className="qualification-subtitle">Situation des normalisations et nouvelles apparitions</h3><div className="qualification-table-wrap compact"><table className="qualification-table movement-table"><thead><tr><th>Responsabilité</th><th className="normalized-head">Normalisé</th><th className="new-degradation-head">Nouvelle dégradation</th><th>Différence</th></tr></thead><tbody>{movementRows.map((row) => <tr key={row.responsibility}><td>{row.responsibility}</td><td className="good-number">{row.normalized || ""}</td><td className="bad-number">{row.newDegradation || ""}</td><td className={row.normalized - row.newDegradation < 0 ? "bad-number" : "good-number"}>{row.normalized - row.newDegradation}</td></tr>)}<tr className="total-row"><td>Total</td><td className="normalized-cell">{movementTotal.normalized}</td><td className="new-degradation-cell">{movementTotal.newDegradation}</td><td className={movementTotal.normalized - movementTotal.newDegradation < 0 ? "bad-number" : "good-number"}>{movementTotal.normalized - movementTotal.newDegradation}</td></tr></tbody></table></div></section>;
}
