"use client";
import { RotateCcw, X } from "lucide-react";
import { useEffect, useState } from "react";
import { BANDS, defaultSettings, type Settings } from "@/lib/types/telecom";
export function SettingsDrawer({ open, settings, onClose, onApply }: { open: boolean; settings: Settings; onClose: () => void; onApply: (next: Settings) => void }) {
  const [draft, setDraft] = useState(settings); useEffect(() => setDraft(settings), [settings, open]); if (!open) return null;
  const set = (key: keyof Settings, value: number) => setDraft((prev) => ({ ...prev, [key]: value }));
  const apply = () => { if (Math.abs(draft.throughputWeight + draft.prbWeight - 1) > .0001) { alert("Les poids Débit et PRB doivent totaliser 100 %."); return; } if (draft.evolutionStable < 0 || draft.evolutionStrong < draft.evolutionStable) { alert("Les seuils IEA-E doivent vérifier 0 ≤ stable ≤ forte amélioration."); return; } onApply(draft); onClose(); };
  return <><div className="drawer-backdrop" onClick={onClose}/><aside className="settings-drawer"><div className="drawer-title"><div><span>PARAMÈTRES</span><h2>Méthodologie IEA-R / IEA-E</h2></div><button onClick={onClose}><X /></button></div><div className="settings-body"><h3>Seuils débit DL (Mbps) — IEA-R</h3>{BANDS.map((band) => <label key={band}>{band}<input type="number" min="0" step=".1" value={draft.dlThresholds[band]} onChange={(e) => setDraft((p) => ({ ...p, dlThresholds: { ...p.dlThresholds, [band]: Number(e.target.value) } }))} /></label>)}<label>Seuil PRB DL BH (%) — IEA-R<input type="number" min="0" max="100" value={draft.prbThreshold} onChange={(e) => set("prbThreshold", Number(e.target.value))}/></label><h3>Pondération IEA-R & IEA-E</h3><label>Débit DL<input type="number" min="0" max="1" step=".05" value={draft.throughputWeight} onChange={(e) => set("throughputWeight", Number(e.target.value))}/></label><label>PRB DL<input type="number" min="0" max="1" step=".05" value={draft.prbWeight} onChange={(e) => set("prbWeight", Number(e.target.value))}/></label><h3>Classification IEA-R — Résorption</h3>{([['veryEffective','Très efficace'],['effective','Efficace'],['partial','Amélioration partielle'],['regression','Régression']] as const).map(([key,label]) => <label key={key}>{label}<input type="number" step=".05" value={draft[key]} onChange={(e) => set(key, Number(e.target.value))}/></label>)}<h3>Classification IEA-E — Évolution</h3><label>Stable ± (%)<input type="number" min="0" max="1" step=".01" value={draft.evolutionStable} onChange={(e) => set("evolutionStable", Number(e.target.value))}/></label><label>Forte évolution ± (%)<input type="number" min="0" max="1" step=".01" value={draft.evolutionStrong} onChange={(e) => set("evolutionStrong", Number(e.target.value))}/></label></div><div className="drawer-actions"><button className="ghost" onClick={() => setDraft(defaultSettings)}><RotateCcw size={15}/> Restaurer</button><button className="primary" onClick={apply}>Appliquer</button></div></aside></>;
}
