import { BANDS, type SectorImpactResult, type Settings } from "@/lib/types/telecom";

const pct = (v?: number) => v === undefined ? null : v;
const date = (v?: Date) => v || null;
const name = (date: Date) => `TRD_Action_Effectiveness_${date.toISOString().slice(0, 10).replaceAll("-", "")}.xlsx`;
const statusOrder = ["Très efficace", "Efficace", "Amélioration partielle", "Impact faible / non significatif", "Régression", "Non mesurable"];
function median(values: number[]) { const a = [...values].sort((x, y) => x - y); return a.length ? a[Math.floor(a.length / 2)] : null; }
function detailRows(results: SectorImpactResult[]) { return results.map((r) => { const row: Record<string, unknown> = { Secteur: r.sector, DR: r.after.dr, Plaque: r.after.plaque, Vendor: r.after.vendor, Responsabilité: r.after.responsibility, Action: r.after.action, Qualif: r.degradationStatus, "Date Action": date(r.dateAction), "Dégradation initiale": r.before.degradedBands.join("+"), "Dégradation après": r.after.degradedBands.join("+"), "Bandes chargées initiales": r.before.chargedBands.join("+"), "Gap DL Avant": r.gapDlBefore, "Gap DL Après": r.gapDlAfter, "TRD Débit": pct(r.trdThroughput), "Gap PRB Avant": r.gapPrbBefore, "Gap PRB Après": r.gapPrbAfter, "TRD PRB": pct(r.trdPrb), "IEA Action": pct(r.iea), "Statut Action": r.actionEffectiveness, "Statut Dégradation": r.degradationStatus, Conclusion: r.conclusion, "Confiance mesure": r.confidence, "Evolution bande dégradée": r.bandMigration }; for (const band of BANDS) { const b = r.bandResults[band]; Object.assign(row, { [`${band} DL Avant`]: b.throughputBefore, [`${band} DL Après`]: b.throughputAfter, [`Gain DL ${band} %`]: pct(b.throughputGain), [`${band} PRB Avant`]: b.prbBefore, [`${band} PRB Après`]: b.prbAfter, [`Soulagement PRB ${band} pts`]: b.prbRelief }); } return row; }); }
export async function exportResults(results: SectorImpactResult[], allResults: SectorImpactResult[], settings: Settings, beforeFile: string, afterFile: string) {
  const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); workbook.creator = "Network Action Effectiveness Analyzer"; workbook.created = new Date();
  const detail = workbook.addWorksheet("Comparatif_TRD", { views: [{ state: "frozen", ySplit: 1 }] }); const rows = detailRows(results); detail.columns = Object.keys(rows[0] || detailRows(allResults)[0] || { Secteur: "" }).map((header) => ({ header, key: header, width: header === "Secteur" ? 36 : header === "Conclusion" || header === "Action" ? 30 : 18 })); rows.forEach((row) => detail.addRow(row)); detail.autoFilter = { from: "A1", to: { row: Math.max(1, detail.rowCount), column: detail.columnCount } };
  const dashboard = workbook.addWorksheet("Dashboard_TRD", { views: [{ state: "frozen", ySplit: 1 }] }); dashboard.addRow(["Dashboard TRD / IEA", "Valeur"]); const measurable = results.filter((r) => r.iea !== undefined); dashboard.addRows([["Secteurs affichés", results.length], ["Actions mesurables", measurable.length], ["Secteurs normalisés", results.filter((r) => /^normalis/i.test(r.degradationStatus)).length], ["Persiste avec amélioration", results.filter((r) => /^persiste/i.test(r.degradationStatus) && (r.iea ?? -Infinity) >= .2).length], ["Régressions", results.filter((r) => r.actionEffectiveness === "Régression").length], ["IEA moyen", measurable.length ? measurable.reduce((s, r) => s + (r.iea || 0), 0) / measurable.length : null], []]); dashboard.addRow(["Répartition statut action", "Secteurs", "%"]); statusOrder.forEach((status) => { const count = results.filter((r) => r.actionEffectiveness === status).length; dashboard.addRow([status, count, results.length ? count / results.length : 0]); }); dashboard.addRow([]); dashboard.addRow(["Responsabilité", "Secteurs", "Mesurables", "IEA moyen"]); const groups = new Map<string, SectorImpactResult[]>(); results.forEach((r) => { const k = r.after.responsibility || "Non renseigné"; groups.set(k, [...(groups.get(k) || []), r]); }); [...groups.entries()].sort(([a],[b]) => a.localeCompare(b)).forEach(([label, values]) => { const measurableValues = values.filter((r) => r.iea !== undefined); dashboard.addRow([label, values.length, measurableValues.length, measurableValues.length ? measurableValues.reduce((s, r) => s + (r.iea || 0), 0) / measurableValues.length : null]); }); dashboard.addRow([]); dashboard.addRow(["Bande", "Gain débit médian", "Soulagement PRB médian"]); BANDS.forEach((band) => dashboard.addRow([band, median(results.map((r) => r.bandResults[band].throughputGain).filter((v): v is number => v !== undefined)), median(results.map((r) => r.bandResults[band].prbRelief).filter((v): v is number => v !== undefined))]));
  const parameters = workbook.addWorksheet("Parametres_TRD"); parameters.addRows([["Paramètre", "Valeur"], ["Seuil DL L1800", settings.dlThresholds.L1800], ["Seuil DL L2100", settings.dlThresholds.L2100], ["Seuil DL L2600", settings.dlThresholds.L2600], ["Seuil DL L800", settings.dlThresholds.L800], ["Seuil PRB", settings.prbThreshold], ["Poids TRD débit", settings.throughputWeight], ["Poids TRD PRB", settings.prbWeight], ["Seuil Très efficace", settings.veryEffective], ["Seuil Efficace", settings.effective], ["Seuil Amélioration partielle", settings.partial], ["Seuil Régression", settings.regression], ["Date d'analyse", new Date()], ["Fichier BEFORE", beforeFile], ["Fichier AFTER", afterFile], ["Secteurs communs", allResults.length], [], ["Méthodologie", "TRD measures the proportion of the initial degradation gap eliminated after corrective action."], ["Note", "Two-snapshot qualification is indicative. Stronger causal qualification requires comparable BH/time windows, traffic and active-user control."]]);
  [detail, dashboard, parameters].forEach((sheet) => { sheet.getRow(1).eachCell((cell) => { cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF12355B" } }; cell.font = { bold: true, color: { argb: "FFFFFFFF" } }; cell.alignment = { vertical: "middle", wrapText: true }; }); sheet.columns.forEach((column) => { column.alignment = { vertical: "top", wrapText: true }; }); }); detail.getColumn("Date Action").numFmt = "dd/mm/yyyy"; [detail, dashboard, parameters].forEach((sheet) => sheet.eachRow((row) => row.eachCell((cell) => { if (typeof cell.value === "number" && /(IEA|TRD|Gain|Poids|Seuil Très|Seuil Efficace|Seuil Amélioration|Seuil Régression|%)/.test(String(sheet.getCell(1, cell.col).value))) cell.numFmt = "0.0%"; }))); const ieaColumn = detail.columns.findIndex((c) => c.key === "IEA Action") + 1; if (ieaColumn) detail.addConditionalFormatting({ ref: `${detail.getColumn(ieaColumn).letter}2:${detail.getColumn(ieaColumn).letter}${detail.rowCount}`, rules: [{ type: "colorScale", priority: 1, cfvo: [{ type: "min" }, { type: "percentile", value: 50 }, { type: "max" }], color: [{ argb: "FFFDE2E1" }, { argb: "FFFFEB9C" }, { argb: "FFC6EFCE" }] }] });
  const buffer = await workbook.xlsx.writeBuffer(); const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = name(new Date()); anchor.click(); URL.revokeObjectURL(anchor.href);
}
